In [1]:
# Commented out the below line for installation of pandas if it is already installed
!python3 -m pip install pandas

import pandas as pd

# Define file path
# file_path = "C:\\Users\\Zixuan\\Downloads\\MinFin V1.0.0kc.xlsm"
file_path = "data/Ghana MINFin Energy NCQG.xlsm"
# Load the Excel file and check available sheet names
xls = pd.ExcelFile(file_path)
sheet_names = xls.sheet_names
# Display sheet names
sheet_names

Requirement already satisfied: pandas in c:\users\zixuan\.pyenv\pyenv-win\versions\3.11.0b4\lib\site-packages (2.3.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\zixuan\.pyenv\pyenv-win\versions\3.11.0b4\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: numpy>=1.23.2 in c:\users\zixuan\.pyenv\pyenv-win\versions\3.11.0b4\lib\site-packages (from pandas) (2.3.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\zixuan\.pyenv\pyenv-win\versions\3.11.0b4\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\zixuan\.pyenv\pyenv-win\versions\3.11.0b4\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\zixuan\.pyenv\pyenv-win\versions\3.11.0b4\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

WARNING: You are using pip version 22.0.4; however, version 25.3 is available.
You should consider upgrading via the 'C:\Users\Zixuan\.pyenv\pyenv-win\versions\3.11.0b4\python3.exe -m pip install --upgrade pip' command.
C:\Users\Zixuan\AppData\Local\Temp\ipykernel_38620\1008124685.py:4: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

['Definitions',
 'Visualisation Dashboard',
 'High Level Dashboard',
 'Technology Disag (S1)',
 'Technology Disag (S2)',
 'Financing Baseline',
 'Funding Baseline',
 'Investment Needs',
 'New Infrastructure (Input)']

In [17]:
import sys
sys.modules.pop("MinFin", None)  # clean the cache of MinFin module, in case it is changed between runs.
from MinFin import load_excel_data
# MinFin is a Python module designed specifically for this MINFin model
# We import functions from it   
# df_param_constraints, df_financing_baseline, df_funding_baseline, df_scenarios, df_currencies, df_technologies, df_technologies_classification =  load_excel_data(file_path)


# df_technologies.head(5) # show the first 5 rows of the technologies sheet
result = load_excel_data(file_path)
locals().update(result)

In [19]:
df_technologies.head(5)

,Name,Description,Technology,Classification,Sector
0,PWRBIO001,Biomass power plant,Biomass,Generation Renewable,Power
1,PWRCOA001,Coal power plant,Coal,Generation Fossil-Fuel,Power
2,PWRCSP001,CSP - Without storage,CSP,Generation Renewable,Power
3,PWRCSP002,CSP - With storage,CSP,Generation Renewable,Power
4,PWRDIST,Electricity Distribution,Distribution,Distribution Infrastructure,Power

In [20]:
df_technologies_classification.head(5)

   Technology        Classification
0     Biomass  Generation Renewable
1  Geothermal  Generation Renewable
2    Solar PV  Generation Renewable
3         CSP  Generation Renewable
4  Hydropower  Generation Renewable

In [26]:
df_param_constraints.head(5)
df_investment_needs.head(5)
# df_financing_baseline.head(5)
# df_funding_baseline.head(7)
# df_scenarios.head(5)
# df_currencies.head(5)

                     Name                                        Description
0     Carbon Credit Price   The parameter carbon credit price refers to t...
1            Carbon Price  The parameter carbon price refers to the cost ...
2           CO2 Emissions  The parameter CO2 emissions refers to the tota...
3  Electricity Production  The parameter electricity production refers to...
4              Fixed Cost  The parameter fixed cost refers to the ongoing...